### ISSUE TITLE
Description of Smart Data Framework  Microservices

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/Microservices#12]
As already done for the integration services, descriptions of the microservices of the smart data framework (data hub) must be created. In particular, an overview of the interplay of the microservices need to be created, as well as a detailed description of each microserice.

Elastic.io is responsible for the overall development of these results.

- [x] The responsibility for describing the interactions between the Data Hub services has **Elastic.io** - @drobiazko

The following list shows the responsibilities for the different microservices:
- [ ] Data Hub API _(Lead:  **Elastic.io** - @drobiazko )_
- [ ] Metadata Repository _(Lead:  **Elastic.io** - @drobiazko )_
- [ ] Hierarchy and Relationship Management _(Lead: **WICE** - @hschmidthh )_
- [ ] Notification and Event Bus _(Lead: **WICE** - @hschmidthh )_
- [ ] Master Data Repository _(Lead:  **Elastic.io** - @drobiazko )_
- [x] CRUD Monitoring _(Lead: **WICE** - @hschmidthh )_
- [ ] Conflict-Management _(Lead: **WICE** - @hschmidthh )_
- [ ] Secure Attachement Storage _(Lead:  **Elastic.io** - @drobiazko )_
- [ ] Reporting and Analytics APIs _(Lead: **Basaas** - @sachmerz )_
